frr version 9.0
frr defaults traditional
hostname frr
log syslog informational
no ipv6 forwarding
!
ip route 10.1.0.0/24 Null0
ip route 10.2.0.0/24 Null0
!
router bgp 65002
 bgp router-id 172.20.0.3
 no bgp ebgp-requires-policy
 neighbor 172.20.0.2 remote-as 65001
 neighbor 172.20.0.2 description pathforge
 neighbor 172.20.0.2 timers 10 30
 !
 address-family ipv4 unicast
  neighbor 172.20.0.2 activate
  network 10.1.0.0/24
  network 10.2.0.0/24
 exit-address-family
!
line vty
!
